### ISSUE TITLE
Suggestion: Downgrade log message in handle_msg to trace

### ISSUE THREAD

**Issue by miyachan** [lnx-search/lnx#25]
I'm not sure if you are just suppressing all log output - but in my testing I found that the log message in `handle_msg` (https://github.com/lnx-search/lnx/blob/f290cb8c1bce669eeebafc6feef343e77b70e413/engine/src/index/writer.rs#L102) is too chatty. It logs every operation that happens on the index, and when you are indexing millions of docs it generates a ton of logs (~100GB of logs in my case!). All that disk writing also severely affects performance - my throughput went from 20k docs/s to 40k docs/s by changing `info!` to `trace!`. I don't find that the messages are all that useful enough to be `info!` either.

**Comment by ChillFish8** [comment]
Hmm that seems reasonable, I wonder if if its better to downgrade to debug! Though rather than trace.

**Comment by ChillFish8** [comment]
I've downgraded this to debug! which for general usage should be alright. The only reason why I don't downgrade this further is to trace! is because I use it quite a lot when debugging writer issues and performance especially with the pre-processing behaviour of fast-fuzzy. So I think this is a good compromise.
